services:
  rabbitMQ_server:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    #restart:
  mongodb:
    image: mongo
    ports:
      - 27017
  producer:
    #image: 
    build:
      context: .
      dockerfile: Dockerfile_producer
    container_name: producer
    #restart: 
    ports:
      - 5000:5000
    depends_on:
      - rabbitMQ_server
  ride_matching:
    #image: 
    build:
      context: .
      dockerfile: Dockerfile_ride_matching
    container_name: ride_matching_consumer
    depends_on:
      - producer
    environment:
      - CONSUMER_ID=1
      - PRODUCER_ADDRESS=http://producer:5000
    #deploy:
    #  mode: replicated
    #  replicas: 2
  ride_database:
    #image: 
    build:
      context: .
      dockerfile: Dockerfile_database
    container_name: ride_database_consumer
    #restart: 
    depends_on:
      - producer
      - mongodb
  