# Base image
FROM python:3.8

# Create directory on the image
WORKDIR /app

# Copy requirements
COPY ./requirements_ride_consumer.txt /app/requirements_ride_consumer.txt 

# Install requirements
RUN pip install -r requirements_ride_consumer.txt

# Copy consumer file
COPY ./ride_matching_consumer.py /app/ride_matching_consumer.py 

# Run the comsumer file
CMD ["python", "-u", "ride_matching_consumer.py"]
