# Fill in the YAML configuration for the microservices 

version: "2.1"
services:
  rabbitMQ_server:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart:
  producer:
    image: 
    container_name:
    restart: 
    ports:
    depends_on:
      - rabbitMQ_server
  ride_matching:
    image: 
    container_name: 
    depends_on:
    environment:
      - CONSUMER_ID=
      - PRODUCER_ADDRESS=
  ride_database:
    image: 
    container_name:
    restart: 
    depends_on:
      - producer
  