# Base image
FROM python:3.8

# Create directory on the image
WORKDIR /app

# Copy requirements
COPY ./requirements_database.txt /app/requirements_database.txt 

# Install requirements
RUN pip install -r requirements_database.txt

# Copy consumer file
COPY ./database_consumer.py /app/database_consumer.py 

# Run the comsumer file
CMD ["python", "-u", "database_consumer.py"]
